models/User.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string|null $confirmation_token
 * @property int $status
 * @property int|null $superadmin
 * @property string $created_at
 * @property string|null $branch_id
 */
class User extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{
    // holds the password confirmation word
    public $initialPassword;
    
    //will hold the encrypted password for update actions.
    public $confirmPassword;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'auth_key', 'password_hash', 'created_at', 'initialPassword', 'confirmPassword'], 'required'],
            [['status', 'superadmin'], 'integer'],
            [['created_at'], 'safe'],
            [['username', 'password_hash', 'confirmation_token', 'branch_id'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            ['confirmPassword', 'compare', 'compareAttribute' => 'initialPassword'],
            [['initialPassword'],'string', 'min' => 5, 'max' => 32]
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['create'] = ['username', 'initialPassword', 'confirmPassword', 'superadmin', 'branch_id'];
        $scenarios['login'] = ['username', 'initialPassword'];

        return $scenarios;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {

            if ($this->superadmin == 0) {
                $auth = Yii::$app->authManager;
                $roleObject = $auth->getRole('super');
                $auth->assign($roleObject, $this->id);
            }

            else if ($this->superadmin == 1) {

                $auth = Yii::$app->authManager;
                $roleObject = $auth->getRole('supervisor');
                $auth->assign($roleObject, $this->id);
            }

            else if ($this->superadmin == 2) {

                $auth = Yii::$app->authManager;
                $roleObject = $auth->getRole('admin');
                $auth->assign($roleObject, $this->id);
            }
        }
        
    }

    public function beforeSave($insert)
    {

        if (parent::beforeSave($insert)) {

            if ($this->isNewRecord) {
                $this->genarateAuthKey();
                $this->hashPassword();
                $this->created_at = date('Y-m-d H:i:s');
                
                return true;
            }

            return false;
        }
    }

    public function beforeDelete()
    {
        if (!parent::beforeDelete()) {
            return false;
        }

        $auth = Yii::$app->authManager;
        $roleObject = $auth->getRole('admin');
        $auth->revoke($roleObject, $this->id);
        
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'confirmation_token' => 'Confirmation Token',
            'status' => 'Status',
            'superadmin' => 'Superadmin',
            'created_at' => 'Created At',
            'branch_id' => 'Branch ID',
            'initialPassword' => 'Password',
            'confirmPassword' => 'Confirm Password',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function genarateAuthKey()
    {
        $this->auth_key = Yii::$app->getSecurity()->generateRandomString();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function hashPassword()
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($this->initialPassword);
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\Branch;
use app\models\LoginForm;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['create', 'index', 'update', 'view', 'branch', 'delete'],
                        'allow' => true,
                        'roles' => ['super']
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'city' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->scenario = 'create';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionBranch()
    {
        if (isset($_POST['depdrop_parents'])) {

            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $parents = $_POST['depdrop_parents'];
            if ($parents != null && $parents[0] == 0) {
                $city = Branch::find()->all();
                return ['output'=>$city, 'selected'=> ''];    
            }

            return ['output'=>'', 'selected'=> ''];
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionLogin()
    {

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
        
        /*
        $model = new LoginForm();

        if($model->load(Yii::$app->request->post())) {

            $password = $model->initialPassword;
            $user = $this->findModel(['username' => $model->username]);
            if ($user->validatePassword($password))  {
                $this->redirect('\user\index');
            }

        }

        return $this->render('login', [
            'model' => $model,
        ]);
        */
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\controllers\users_traits\LogTrait;
use app\controllers\users_traits\RoleTrait;
use app\controllers\users_traits\UserTrait;
use app\models\users\forms\RecoveryForm;
use app\models\users\forms\RegistrationForm;
use app\traits\LogingTrait;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

class UsersController extends Controller
{
    use RoleTrait;
    use UserTrait;
    use LogTrait;
    use LogingTrait;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'roles' => ['?'],
                        'allow' => true,
                        'actions' => ['registration', 'recovery', 'message']
                    ],
                    [
                        'roles' => ['developer'],
                        'allow' => true,
                    ],
                ],
            ],
        ];
    }

    public function actionRegistration()
    {
        $model = new RegistrationForm();

        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            
	    	return ActiveForm::validate($model);
        }
        
        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {

            if ($model->save()) {
                \Yii::$app->getSession()->setFlash('success', "$model->username has been created");
                $this->createTransactionLog('[CREATE] at User Table');

                return $this->redirect(\Yii::$app->request->referrer ?: \Yii::$app->homeUrl);
            }
        }

        return $this->renderAjax('registration', [
            'model' => $model,
        ]);
    }

    public function actionRecovery()
    {
        $model = new RecoveryForm();

        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            
	    	return ActiveForm::validate($model);
        }
        
        if ($model->load(\Yii::$app->request->post()) && $model->sendRecoveryMessage()) {
            \Yii::$app->getSession()->setFlash('success','Kata sandi baru telah dikirim ke email anda.');
            return $this->redirect('/users/message');
        }
        return $this->render('recovery', [
            'model' => $model,
        ]);
    }

    public function actionMessage()
    {
        return $this->render('message');
    }
}

views/user/_form.php
<?php

use kartik\depdrop\DepDrop;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'initialPassword')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'confirmPassword')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'superadmin')->widget(Select2::className(), [
        'data' => [0, 1, 2],
        'options' => [
            'placeholder' => 'Pilih Superadmin...',
            'id' => 'superadmin'
        ],
        'pluginOptions' => [
            'allowClear' => true
        ]
    ]) ?>

    <?= $form->field($model, 'branch_id')->widget(DepDrop::className(), [
        'options'=>['id'=>'city_id'],
        'type' => DepDrop::TYPE_SELECT2,
        'pluginOptions' => [
            'depends' => ['superadmin'],
            'placeholder' => "Pilih Ma'had...",
            'url' => Url::to(['/user/branch']),
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'confirmation_token') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'superadmin') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'branch_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;
use kartik\depdrop\DepDrop;
use kartik\select2\Select2;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'initialPassword')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'confirmPassword')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'superadmin')->widget(Select2::className(), [
        'data' => [0, 1, 2],
        'options' => [
            'placeholder' => 'Pilih Superadmin...',
            'id' => 'superadmin'
        ],
        'pluginOptions' => [
            'allowClear' => true
        ]
    ]) ?>

    <?= $form->field($model, 'branch_id')->widget(DepDrop::className(), [
        'options'=>['id'=>'city_id'],
        'type' => DepDrop::TYPE_SELECT2,
        'pluginOptions' => [
            'depends' => ['superadmin'],
            'placeholder' => "Pilih Ma'had...",
            'url' => Url::to(['/user/branch']),
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

</div>

views/user/index.php
<?php

use app\models\Branch;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create User', ['/site/registration'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],

            'id',
            'username',
            //'auth_key',
            //'password_hash',
            //'confirmation_token',
            //'status',
            'superadmin' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'superadmin',
                'value' => function($model) {
                    $query = Yii::$app->db->createCommand(" 
                        SELECT description FROM auth_assignment a 
                        LEFT OUTER JOIN auth_item i on i.name = a.item_name
                        WHERE a.user_id = $model->id
                    ")->queryAll();
                    return $query[0]['description'];
                },
            ],
            //'created_at',
            'branch' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'superadmin',
                'value' => function($model) {
                    if (($query = Branch::findOne(['id' => $model->branch_id])) !== null) {
                        return $query->name;
                    }
                    return '-';
                },
            ],

            ['class' => 'kartik\grid\ActionColumn'],
        ],
        'pjax' => true,
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'responsiveWrap' => false,
        'hover' => true,
        'floatHeader' => false,
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/user/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'confirmation_token',
            'status',
            'superadmin',
            'created_at',
            'branch_id',
        ],
    ]) ?>

</div>