models/Branch.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "branch".
 *
 * @property string $id ID
 * @property int $city_id Kota
 * @property int $province_id Provinsi
 * @property string $address Alamat
 * @property string|null $maps Lokasi Maps
 * @property string $name Nama
 * @property string $cheif Mudir
 * @property int $active_student Santri Aktif
 * @property int $total_student Total Santri
 *
 * @property City $city
 * @property Province $province
 * @property Graduated[] $graduateds
 * @property Student[] $students
 */
class Branch extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'branch';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'city_id', 'province_id', 'address', 'name', 'cheif'], 'required'],
            [['city_id', 'province_id', 'active_student', 'total_student'], 'integer'],
            [['address'], 'string'],
            [['id', 'maps', 'name', 'cheif'], 'string', 'max' => 255],
            [['id'], 'unique'],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => City::className(), 'targetAttribute' => ['city_id' => 'id']],
            [['province_id'], 'exist', 'skipOnError' => true, 'targetClass' => Province::className(), 'targetAttribute' => ['province_id' => 'id']],
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['create'] = ['city_id', 'province_id', 'address', 'name', 'cheif', 'maps'];
        $scenarios['updateStudent'] = ['active_student', 'total_student'];
        $scenarios['updateGraduated'] = ['total_student'];


        return $scenarios;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'city_id' => 'Kota',
            'province_id' => 'Provinsi',
            'address' => 'Alamat',
            'maps' => 'Lokasi Maps',
            'name' => 'Nama',
            'cheif' => 'Mudir',
            'active_student' => 'Santri Aktif',
            'total_student' => 'Total Santri',
        ];
    }

    /**
     * Gets query for [[City]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCity($province = null)
    {
        return $this->hasOne(City::className(), ['id' => 'city_id']);
    }

    /**
     * Gets query for [[Province]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProvince()
    {
        return $this->hasOne(Province::className(), ['id' => 'province_id']);
    }

    /**
     * Gets query for [[Graduateds]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGraduateds()
    {
        return $this->hasMany(Graduated::className(), ['branch_id' => 'id']);
    }

    /**
     * Gets query for [[Students]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getStudents()
    {
        return $this->hasMany(Student::className(), ['branch_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {

            if ($this->isNewRecord) {
                $province = new Province();
                $province = $province->findOne($this->province_id);
                $province->total_branch = $province->total_branch + 1;
                $this->id = sprintf('%04s%03s',$this->city_id, $province->total_branch);

                $province->save();
                
                return true;
            }

            return true;
        }
        return false;
    }

    public function beforeDelete()
    {
        if (!parent::beforeDelete()) {
            return false;
        }

        $student = new Student();
        $graduated = new Graduated();
        $user = new User();
        $province = new Province();

        $province = $province->findOne($this->province_id);
        $province->total_branch = $province->total_branch - 1;
        
        $student->deleteAll("branch_id = $this->id");
        $graduated->deleteAll("branch_id = $this->id");
        $user->deleteAll("branch_id = $this->id");

        return true;
    }
}

controllers/BranchController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Branch;
use app\models\BranchSearch;
use app\models\City;
use app\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;

/**
 * BranchController implements the CRUD actions for Branch model.
 */
class BranchController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['create', 'index', 'update', 'view', 'city', 'delete'],
                        'allow' => true,
                        'roles' => ['super']
                    ],
                    [
                        'actions' => ['index', 'view',],
                        'allow' => true,
                        'roles' => ['supervisor'],
                    ],
                    [
                        'actions' => ['index', 'update', 'view',],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'city' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Branch models.
     * @return mixed
     */
    public function actionIndex()
    {
        $branch_id = User::findOne(Yii::$app->user->getId())->branch_id;
        if ( Yii::$app->user->can('admin')) {
            $this->redirect("branch/view?id=$branch_id");
        }
        $searchModel = new BranchSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $city = ArrayHelper::map(City::find()->all(), 'id', 'name');
        
        if (isset(Yii::$app->request->get('BranchSearch')['province_id'])) {
            $request = Yii::$app->request;
            $parent = $request->get('BranchSearch')['province_id'];

            if(!empty($parent)) {
                $city = ArrayHelper::map(City::findAll(['province_id' => $parent]), 'id', 'name');
                
                return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'city' => $city,
                ]);
            }
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'city' => $city,
        ]);
    }

    /**
     * Displays a single Branch model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $branch_id = User::findOne(Yii::$app->user->getId())->branch_id;
        if ($branch_id == $id || Yii::$app->user->can('super') || Yii::$app->user->can('supervisor')) {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }

        throw new ForbiddenHttpException("Access Denied");
        
    }

    /**
     * Creates a new Branch model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Branch();
        $model->scenario = 'create';

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save()) {
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', "Ma'had Berhasil di Daftarkan");
                    return $this->refresh();
                }
                Yii::$app->session->setFlash('error', "Ma'had Gagal di Daftarkan.");

            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Branch model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $branch_id = User::findOne(Yii::$app->user->getId())->branch_id;
        if ($branch_id == $id || Yii::$app->user->can('super')) {
                $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        }

        throw new ForbiddenHttpException("Access Denied");


        
    }

    public function actionCity()
    {
        if (isset($_POST['depdrop_parents'])) {

            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $city = City::findAll(['province_id' => $parents[0]]);
                return ['output'=>$city, 'selected'=> ''];    
            }

            return ['output'=>'', 'selected'=> ''];
        }
    }

    /**
     * Deletes an existing Branch model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Branch model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Branch the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Branch::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/branch/_form.php
<?php

use app\models\Province;
use kartik\depdrop\DepDrop;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Branch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="branch-form">

    <?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'province_id')->widget(Select2::className(), [
        'data' => ArrayHelper::map(Province::find()->all(), 'id', 'name'),
        'options' => [
            'placeholder' => 'Pilih Provinsi ...',
            'id' => 'province_id',
        ],
        'pluginOptions' => [
            'allowClear' => true
        ]
    ]) ?>

    <?= $form->field($model, 'city_id')->widget(DepDrop::className(), [
        'options'=>['id'=>'city_id'],
        'type' => DepDrop::TYPE_SELECT2,
        'pluginOptions' => [
            'depends' => ['province_id'],
            'placeholder' => 'Pilih Kota/Kab...',
            'url' => Url::to(['/branch/city']),
        ],
    ]) ?>

    <?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'maps')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cheif')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/branch/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BranchSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="branch-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'city_id') ?>

    <?= $form->field($model, 'province_id') ?>

    <?= $form->field($model, 'address') ?>

    <?= $form->field($model, 'maps') ?>

    <?php // echo $form->field($model, 'name') ?>

    <?php // echo $form->field($model, 'cheif') ?>

    <?php // echo $form->field($model, 'active_student') ?>

    <?php // echo $form->field($model, 'total_student') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/branch/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Branch */

$this->title = 'Create Ma\'had';
$this->params['breadcrumbs'][] = ['label' => 'Branches', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="branch-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/branch/index.php
<?php

use app\models\Province;
use kartik\select2\Select2;
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\BranchSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ma\'had';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="branch-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Branch', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<div class="box-body table-responsive no-padding">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],

            'id' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'id',
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;', 'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],
            'name' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'name',
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;', 'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],
            'cheif' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'cheif',
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;', 'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],
            'province.name' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'province.name',
                'label' => 'provinsi',
                'filter' => Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'province_id',
                    'data' => ArrayHelper::map(Province::find()->all(), 'id', 'name'),
                    'options' => ['placeholder' => 'Provinsi...'],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ]),
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;', 'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],
            'city.name' => [
                'class' => 'kartik\grid\DataColumn',
                'label' => 'Kota',
                'attribute' => 'city.name',
                'filter' => Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'city_id',
                    'data' => $city,
                    'options' => ['placeholder' => 'Kota/Kab...'],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ]),
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;', 'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],
            //'address:ntext',
            'maps' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'maps',
                'filter' => false,
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;',  'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],
            'active_student' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'active_student',
                'filter' => false,
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;', 'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],
            'total_student' => [
                'class' => 'kartik\grid\DataColumn',
                'attribute' => 'total_student',
                'filter' => false,
                'contentOptions' => function ($model, $key, $index, $grid) {
                
                    return ['id' => $model['id'], 'style' => 'cursor: pointer;', 'onclick' => 'window.location.href = "'.Url::to(['view', 'id' => $model->id]).'";'];
                
                },
            ],

            ['class' => 'kartik\grid\ActionColumn'],
        ],
        'containerOptions' => ['style' => 'overflow: auto'], 
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'containerOptions' => ['style'=>'overflow: auto'], 
        'beforeHeader'=>[
            [
                'columns'=>[
                    ['content'=> 'List Santri', 'options'=>['colspan'=>12, 'class'=>'text-center']],
                ], 
                'options'=>['class'=>'skip-export'] 
            ]
        ],
        'exportConfig' => [
            GridView::PDF => [
                'label' => 'Save as PDF',
                'pdfConfig' => [
                    'methods' => [
                        'SetTitle' => 'Ma\'had - Alaskar.com',
                        'SetSubject' => '',
                        'SetHeader' => ['Ma\'had Al Askar||Generated On: ' . date("r")],
                        'SetFooter' => ['|Page {PAGENO}|'],
                    ]
                ],
            ],
            GridView::EXCEL => ['label' => 'Save as EXCEL'], 
            GridView::CSV => ['label' => 'Save as CSV'], 
        ],
          
        'toolbar' =>  [
            '{export}', 
        ],
        'pjax' => true,
        'striped' => true,
        'condensed' => false,
        'hover' => true,
        'responsive' => true,
        'responsiveWrap' => false,
        'tableOptions' =>[

        ],
        'panel' => [
            'type' => GridView::TYPE_SUCCESS,
            'heading' => 'Ma\'had',
        ],
    ]); ?>
</div>
    <?php Pjax::end(); ?>

</div>

views/branch/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Branch */

$this->title = 'Update Ma\'had: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Branches', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="branch-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/branch/view.php
<?php

use app\models\Graduated;
use app\models\Student;
use app\models\StudentSearch;
use yii\widgets\DetailView;
use yii\bootstrap\Modal;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Branch */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Branches', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="branch-view">

    <h1><?= Html::encode($this->title) ?></h1>

        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>

        <?php
        $data = new ActiveDataProvider([
                'query' => Student::find()->where(['branch_id' => $model->id]),
                'pagination' => [
                    'pageSize' => 10,
                ],
            ]);
            $search = new StudentSearch();
            Modal::begin([
                'header' => '<h2>Santri</h2>',
                'toggleButton' => ['label' => 'Santri', 'class' => 'btn  btn-success'],
            ]);
                echo GridView::widget([
                    'dataProvider' => $data,
                    'columns' => [
                        'name',
                        'doe' => [
                            'class' => 'yii\grid\DataColumn',
                            'label' => 'Tanggal Muqim',
                            'attribute' => 'doe',
                            'value' =>  function($model) {
                                            return date('d M Y', strtotime($model->__get('doe')));
                            },
                        ],
                    ],
                ]);
            Modal::end();
        ?>

        <?php
            $data = new ActiveDataProvider([
                'query' => Graduated::find()->where(['branch_id' => $model->id]),
                'pagination' => [
                    'pageSize' => 10,
                ],
            ]);
            $search = new StudentSearch();
            Modal::begin([
                'header' => '<h2>Alumni</h2>',
                'toggleButton' => ['label' => 'Alumni', 'class' => 'btn  btn-warning'],
            ]);
                echo GridView::widget([
                    'dataProvider' => $data,
                    'columns' => [
                        'name',
                        'doe' => [
                            'class' => 'yii\grid\DataColumn',
                            'label' => 'Tanggal Muqim',
                            'attribute' => 'doe',
                            'value' =>  function($model) {
                                            return date('d M Y', strtotime($model->__get('doe')));
                            },
                        ],
                        'dog' => [
                            'class' => 'yii\grid\DataColumn',
                            'label' => 'Tanggal Muqim',
                            'attribute' => 'doe',
                            'value' =>  function($model) {
                                            return date('d M Y', strtotime($model->__get('doe')));
                            },
                        ],
                    ],
                ]);
            Modal::end();
        ?>
        <div style="margin: 10px;"></div>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'city.name',
            'province.name',
            'address:ntext',
            'maps',
            'name',
            'cheif',
            'active_student',
            'total_student',
        ],
    ])
    
    ?>

</div>